### ISSUE TITLE
pg_easy_check can't work with GCP Cloud SQL

### ISSUE THREAD

**Issue by pcboy** [shayonj/pg_easy_replicate#15]
On Cloud SQL (GCP). The only super user is user `cloudsqladmin`.  
It is not possible to log in as `cloudsqladmin`.  

Problem is pg_easy_replicate then fails with:  
`User on source database should be a superuser`

Superuser privileges should not be needed, as described here: https://cloud.google.com/sql/docs/postgres/replication/configure-logical-replication

All you need is REPLICATION.

**Comment by shayonj** [comment]
oh interesting! I haven't used it on GCP but only on AWS and some self managed PG on kube/VM, so appreciate you opening this issue. 

The reason it checks for superuser is to also ensure that the lib can create a new user to perform the orchestration. The new user that is created ([ref](https://github.com/shayonj/pg_easy_replicate/blob/f2d6d3850ff3f41ef30cd0a355ec4057c4f1ebc3/lib/pg_easy_replicate/helper.rb#L25)) is used for setting up the replication and also help orchestrate the switchover; like when killing connections to ensure that the connection between the two databases isn't severed, but any other connections to the source DB from the original user (in the passed in conn string) is strictly READ ONLY.

That said, we can perhaps relax the requirement, so instead of checking for superuser, we can check to ensure that the connected is able to

- `CREATE ROLE`
- Grant `REPLICATION` on the newly created role
- Lastly, the new role is also able to perform `ALTER ROLE` on the user from the connection string (so that the source database can be put into READ ONLY). 

I am happy to look into this. Can you confirm that in your set up, if the user you are connecting with has privileges to be able to create new role?

**Comment by pcboy** [comment]
I see.

> I am happy to look into this. Can you confirm that in your set up, if the user you are connecting with has privileges to be able to create new role?

Yes no problem to create a new role.

**Comment by shayonj** [comment]
There is now support for special user roles from aws and gcp. More instructions here: https://github.com/shayonj/pg_easy_replicate#bootstrap-and-config-check-with-special-user-role-in-aws-or-gcp

Let me know if you run into any issues. Thanks for your report!
