### ISSUE TITLE
WALs are rising during the synchronization in directory /var/lib/postgresql/16/main/pg_wal/

### ISSUE THREAD

**Issue by algoritmsystems** [shayonj/pg_easy_replicate#166]
I 'm restoring the data from standalone postgresql v14 to the postgresql cluster v16.
First I did bootstrap:
>pg_easy_replicate bootstrap --group-name database-cluster-1 --copy-schema

Then started replication:
>pg_easy_replicate start_sync --group-name database-cluster-dmed --track-ddl

Replication and synchronization went smoothly, without errors between instances!
But wals on one node are rising:
on node1 (leader):
108G    /var/lib/postgresql/16/main/base/
8.1G    /var/lib/postgresql/16/main/pg_wal/

on node2 (replica):
108G    /var/lib/postgresql/16/main/base/
94G     /var/lib/postgresql/16/main/pg_wal/ and still rising...

tracking and applying DDL not helped:
pg_easy_replicate list_ddl_changes -g database-cluster-1
pg_easy_replicate apply_ddl_change -g database-cluster-1

Why wals directory is rising and how to solve this issue? How to correctrly configure this on both sides?
Please help!
Thanks in advance!

**Comment by shayonj** [comment]
I reckon these two are related - https://github.com/shayonj/pg_easy_replicate/issues/167#issuecomment-2388509231

If so, then yes, the WAL accumulation is expected because most tables in the initial copy/sync phase, and the accumulated WAL is likely from the current activity on the tables. 

Once they complete, logical replication will replay all the accumulated WAL logs and those should eventually free up. 

Does this help? Happy to elaborate more

P.S Def keep an eye on the disk space :)

**Comment by algoritmsystems** [comment]
Thanks @shayonj ! 
I synchronized the data for about 5 hours, so I need to wait a little longer, so my database is more than 100 GB too..

**Comment by shayonj** [comment]
Yeah that will do it. One thing that I found useful in the past is scaling up the target DB in CPU and memory before starting sync and that helps. If its an option in future.
