### ISSUE TITLE
Drop and re-create indices for faster catchup on large databases

### ISSUE THREAD

**Issue by shayonj** [shayonj/pg_easy_replicate#8]
On larger databases, the initial COPY can be slow, depending on the database engine and storage type this behavior may not be acceptable. Part of the reason why COPY can be slow is because each batched write id updating the index. So before creating the subscription we can capture all indices in `groups` table, drop it and create the subscription. Once all tables have `replicating` stage, we can re-add the indices.

**Comment by PikachuEXE** [comment]
I got this written in my article about using logical replication to upgrade PSQL
https://dev.to/pikachuexe/postgresql-logical-replication-for-upgrade-41hl - `Failed Attempts #2`

**Comment by shayonj** [comment]
Closed via https://github.com/shayonj/pg_easy_replicate/pull/81

**Comment by TrueCarry** [comment]
> Closed via #81

Can't start_sync, because it tries to drop indices in wrong order:
Starting sync failed: PG::DependentObjectsStillExist: ERROR:  cannot drop index auth_tokens_auth_attempt_id_key because constraint auth_tokens_auth_attempt_id_key on table auth_tokens requires it
HINT:  You can drop constraint auth_tokens_auth_attempt_id_key on table auth_tokens instead.

**Comment by shayonj** [comment]
ah! i see. thanks for the report. Is that the foreign key constraint?

**Comment by shayonj** [comment]
0.2.1 is out with the fix https://github.com/shayonj/pg_easy_replicate/releases/tag/v0.2.1

thanks again for the report. let me know if you run into any issues.
